FROM node:16.14.0

# workdir 지정. 반드시 상위에 적을 것(COPY등 경로에 영향을 줘야하기 때문)
# 절대경로여야 함. 상대 경로 ㄴㄴ
WORKDIR /usr/src/app

# 로컬에 있는 package.json을 컨테이너의 ./ 경로에 COPY 종속성 설치해야 하니까
COPY package.json ./
COPY package-lock.json ./

# 종속성 설치(한 번 빌드하면 cache되기 때문에 속도 걱정은 ㄴㄴ)
RUN yarn

# 전체 소스 코드를 다 들고오자. 단, dockerignore는 없어야 함. 
COPY ./ ./

CMD ["node", "app.js"]